// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type CreateProfileDto = {
    /**
     * Уникальный идентификатор пользователя
     */
    userId: string;
    /**
     * Имя
     */
    firstName: string;
    /**
     * Отчество
     */
    middleName: string;
    /**
     * Фамилия
     */
    lastName: string;
};

export type ProfileResponseDto = {
    /**
     * Уникальный идентификатор аккаунта
     */
    id: string;
    /**
     * Уникальный идентификатор пользователя
     */
    userId: string;
    /**
     * Имя
     */
    firstName: string;
    /**
     * Отчество
     */
    middleName: {
        [key: string]: unknown;
    };
    /**
     * Фамилия
     */
    lastName: string;
    /**
     * URL аватара
     */
    avatar: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateProfileDto = {
    /**
     * Имя
     */
    firstName: string;
    /**
     * Отчество
     */
    middleName: string;
    /**
     * Фамилия
     */
    lastName: string;
};

export type PaginationMetaDto = {
    /**
     * Текущая страница
     */
    page: number;
    /**
     * Количество элементов на странице
     */
    limit: number;
    /**
     * Общее количество элементов
     */
    total: number;
    /**
     * Общее количество страниц
     */
    totalPages: number;
    /**
     * Есть ли следующая страница
     */
    hasNext: boolean;
    /**
     * Есть ли предыдущая страница
     */
    hasPrev: boolean;
};

export type ProfilePaginatedResponse = {
    data: Array<ProfileResponseDto>;
    meta: PaginationMetaDto;
};

export type RegisterDto = {
    /**
     * username
     */
    username: string;
    /**
     * password
     */
    password: string;
    /**
     * email
     */
    email: string;
    /**
     * Имя
     */
    firstName: string;
    /**
     * Отчество (при наличии)
     */
    middleName?: string;
    /**
     * Фамилия
     */
    lastName: string;
};

export type UserResponseDto = {
    /**
     * Уникальный идентификатор пользователя
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * email
     */
    email: string;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type LoginDto = {
    /**
     * password
     */
    password: string;
    /**
     * email
     */
    email: string;
};

export type CreateUserDto = {
    /**
     * username
     */
    username: string;
    /**
     * password
     */
    password: string;
    /**
     * email
     */
    email: string;
    /**
     * Имя
     */
    firstName: string;
    /**
     * Отчество (при наличии)
     */
    middleName: string;
    /**
     * Фамилия
     */
    lastName: string;
};

export type AccountResponseDto = {
    /**
     * Уникальный идентификатор аккаунта
     */
    id: string;
    /**
     * Уникальный идентификатор пользователя
     */
    userId: string;
    /**
     * Доступный баланс пользователя
     */
    availableBalance: number;
    /**
     * Замороженные средства пользователя
     */
    frozenBalance: number;
    /**
     * Доступное пространство для статики
     */
    storageQuotaBytes: number;
    /**
     * Использованное пространство
     */
    storageUsedBytes: number;
};

export type FindMeResponseDto = {
    /**
     * Уникальный идентификатор пользователя
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * email
     */
    email: string;
    /**
     * Аккаунт пользователя
     */
    account: AccountResponseDto;
    /**
     * Профиль пользователя
     */
    profile: ProfileResponseDto;
    /**
     * Рабочие пространства пользователя
     */
    workspaces: Array<string>;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type CreateWorkspaceDto = {
    /**
     * Название рабочего пространства
     */
    name: string;
};

export type WorkspaceResponseDto = {
    /**
     * Уникальный идентификатор рабочего пространства
     */
    id: string;
    /**
     * Название рабочего пространства
     */
    name: string;
    /**
     * Является ли workspace созданным по умолчанию
     */
    isDefault: boolean;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type WorkspacePaginatedResponseDto = {
    data: Array<WorkspaceResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateAccountDto = {
    /**
     * Уникальный идентификатор пользователя
     */
    userId: string;
    /**
     * Доступный баланс пользователя
     */
    availableBalance: number;
    /**
     * Замороженные средства пользователя
     */
    frozenBalance: number;
};

export type UpdateAccountDto = {
    /**
     * Уникальный идентификатор пользователя
     */
    userId: string;
    /**
     * Доступный баланс пользователя
     */
    availableBalance: number;
    /**
     * Замороженные средства пользователя
     */
    frozenBalance: number;
};

export type AccountPaginatedResponse = {
    data: Array<AccountResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateProjectDto = {
    /**
     * Название проекта
     */
    title: string;
    picture?: Blob | File;
};

export type ProjectResponseDto = {
    /**
     * Уникальный идентификатор проекта
     */
    id: string;
    /**
     * Уникальный идентификатор владельца проекта
     */
    userId: string;
    /**
     * Заголовок задачи
     */
    title: string;
    /**
     * URL картинки проекта
     */
    picture?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateProjectDto = {
    /**
     * Название проекта
     */
    title: string;
    picture?: Blob | File;
};

export type ProjectPaginatedResponse = {
    data: Array<ProjectResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateTaskDto = {
    /**
     * Заголовок задачи
     */
    title: string;
    /**
     * Описание задачи
     */
    description: string;
    /**
     * Минимальная цена
     */
    minPrice: number;
    /**
     * Максимальная цена
     */
    maxPrice: number;
    /**
     * Статус задачи
     */
    status?: string;
    /**
     * Опубликовать ли задачу
     */
    isPublished?: boolean;
    /**
     * ID рабочего пространства, к которому будет принадлежать задача
     */
    workspaceId?: string;
    /**
     * ID проекта, к которому будет принадлежать задача
     */
    projectId?: string;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds?: Array<string>;
};

export type TaskResponseDto = {
    /**
     * Уникальный идентификатор задачи
     */
    id: string;
    /**
     * Уникальный идентификатор владельца задачи
     */
    userId: string;
    /**
     * Заголовок задачи
     */
    title: string;
    /**
     * Описание задачи
     */
    description: string;
    /**
     * Минимальная цена
     */
    minPrice: number;
    /**
     * Максимальная цена
     */
    maxPrice: number;
    /**
     * Статус задачи
     */
    status: string;
    /**
     * Опубликована ли задача
     */
    isPublished: boolean;
    /**
     * ID рабочего пространства, к которому принадлежит задача
     */
    workspaceId: string;
    /**
     * ID проекта, к которому будет принадлежит задача
     */
    projectId?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds: Array<string>;
};

export type UpdateTaskDto = {
    /**
     * Заголовок задачи
     */
    title: string;
    /**
     * Описание задачи
     */
    description: string;
    /**
     * Минимальная цена
     */
    minPrice: number;
    /**
     * Максимальная цена
     */
    maxPrice: number;
    /**
     * Статус задачи
     */
    status?: string;
    /**
     * Опубликовать ли задачу
     */
    isPublished?: boolean;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds?: Array<string>;
};

export type TaskResponseForDetailsDto = {
    /**
     * Уникальный идентификатор задачи
     */
    id: string;
    /**
     * Владелец задачи
     */
    user: {
        [key: string]: unknown;
    };
    /**
     * Заголовок задачи
     */
    title: string;
    /**
     * Описание задачи
     */
    description: string;
    /**
     * Минимальная цена
     */
    minPrice: number;
    /**
     * Максимальная цена
     */
    maxPrice: number;
    /**
     * Статус задачи
     */
    status: string;
    /**
     * Опубликована ли задача
     */
    isPublished: boolean;
    /**
     * ID рабочего пространства, к которому принадлежит задача
     */
    workspaceId: string;
    /**
     * ID проекта, к которому будет принадлежит задача
     */
    projectId?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
    /**
     * Массив категорий
     */
    categories: Array<string>;
};

export type TaskForDetailsPaginatedResponse = {
    data: Array<TaskResponseForDetailsDto>;
    meta: PaginationMetaDto;
};

export type CreateServiceDto = {
    /**
     * Название услуги
     */
    title: string;
    /**
     * Описание услуги
     */
    description: string;
    /**
     * Цена услуги
     */
    price: number;
    /**
     * Опубликовать ли задачу. По умолчанию true
     */
    isPublished: boolean;
    /**
     * Идентификатор рабочего пространства к которой привязать услугу. Если не указан, будет использоваться пространство по умолчанию
     */
    workspaceId?: string;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds?: Array<string>;
};

export type ServiceResponseDto = {
    /**
     * Уникальный идентификатор услуги
     */
    id: string;
    /**
     * Уникальный идентификатор владельца услуги
     */
    userId: string;
    /**
     * Название услуги
     */
    title: string;
    /**
     * Описание услуги
     */
    description: string;
    /**
     * Цена услуги
     */
    price: number;
    /**
     * Опубликована ли услуга
     */
    isPublished: boolean;
    /**
     * ID рабочего пространства, к которому принадлежит услуга
     */
    workspaceId?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds: Array<string>;
};

export type UpdateServiceDto = {
    /**
     * Название услуги
     */
    title?: string;
    /**
     * Описание услуги
     */
    description?: string;
    /**
     * Цена услуги
     */
    price?: number;
    /**
     * Опубликовать ли услугу
     */
    isPublished?: boolean;
    /**
     * Массив идентификаторов категорий
     */
    categoryIds?: Array<string>;
};

export type ServiceResponseForDetailsDto = {
    /**
     * Уникальный идентификатор услуги
     */
    id: string;
    /**
     * Владелец услуги
     */
    user: {
        [key: string]: unknown;
    };
    /**
     * Название услуги
     */
    title: string;
    /**
     * Описание услуги
     */
    description: string;
    /**
     * Цена услуги
     */
    price: number;
    /**
     * Опубликована ли услуга
     */
    isPublished: boolean;
    /**
     * ID рабочего пространства, к которому принадлежит услуга
     */
    workspaceId?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
    /**
     * Массив категорий
     */
    categories: Array<string>;
};

export type ServiceForDetailsPaginatedResponse = {
    data: Array<ServiceResponseForDetailsDto>;
    meta: PaginationMetaDto;
};

export type CreateContractDto = {
    /**
     * Сумма контракта
     */
    amount: number;
    /**
     * Уникальный идентификатор исполнителя
     */
    contractorId: string;
    /**
     * Уникальный идентификатор задачи (если контракт создан на основе задачи)
     */
    taskId?: string;
    /**
     * Уникальный идентификатор услуги (если контракт создан на основе услуги)
     */
    serviceId?: string;
};

export type ContractResponseDto = {
    /**
     * Уникальный идентификатор контракта
     */
    id: string;
    /**
     * Сумма контракта
     */
    amount: number;
    /**
     * Уникальный идентификатор заказчика
     */
    clientId: string;
    /**
     * Уникальный идентификатор исполнителя
     */
    contractorId: string;
    /**
     * Статус контракта
     */
    status: 'SEND' | 'IN_PROGRESS' | 'ON_HOLD' | 'DELIVERED' | 'COMPLETED' | 'REJECTED';
    /**
     * Дата согласия заказчика
     */
    clientAcceptedAt?: {
        [key: string]: unknown;
    } | null;
    /**
     * Дата согласия исполнителя
     */
    contractorAcceptedAt?: {
        [key: string]: unknown;
    } | null;
    /**
     * Уникальный идентификатор задачи (если контракт создан на основе задачи)
     */
    taskId?: {
        [key: string]: unknown;
    } | null;
    /**
     * Уникальный идентификатор услуги (если контракт создан на основе услуги)
     */
    serviceId?: {
        [key: string]: unknown;
    } | null;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateContractDto = {
    /**
     * Сумма контракта
     */
    amount?: number;
    /**
     * Статус контракта
     */
    status?: 'SEND' | 'IN_PROGRESS' | 'ON_HOLD' | 'DELIVERED' | 'COMPLETED' | 'REJECTED';
    /**
     * Согласие заказчика
     */
    isClientAccepted?: boolean;
    /**
     * Согласие исполнителя
     */
    isContractorAccepted?: boolean;
};

export type ContractPaginatedResponse = {
    data: Array<ContractResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateBidDto = {
    /**
     * Уникальный идентификатор задачи
     */
    taskId: string;
    /**
     * Цена
     */
    amount: number;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
};

export type BidResponseDto = {
    /**
     * Уникальный идентификатор отклика
     */
    id: string;
    /**
     * Уникальный идентификатор владельца отклика
     */
    userId: string;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
    /**
     * Цена
     */
    amount: number;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateBidDto = {
    /**
     * Цена
     */
    amount: number;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
};

export type BidPaginatedResponse = {
    data: Array<BidResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateInvitationDto = {
    /**
     * Заголовок письма
     */
    title: string;
    /**
     * Уникальный идентификатор получателя приглашения
     */
    recipientId: string;
    /**
     * Уникальный идентификатор рабочего пространства
     */
    workspaceId: string;
    /**
     * Уникальный идентификатор проекта
     */
    projectId: string;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
};

export type InvitationResponseDto = {
    /**
     * Уникальный идентификатор приглашения
     */
    id: string;
    /**
     * Заголовок письма
     */
    title: string;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
    /**
     * Уникальный идентификатор отправителя
     */
    senderId: string;
    /**
     * Уникальный идентификатор получателя
     */
    recipientId: string;
    /**
     * Уникальный идентификатор рабочего пространства
     */
    workspaceId?: {
        [key: string]: unknown;
    };
    /**
     * Уникальный идентификатор проекта
     */
    projectId?: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateInvitationDto = {
    /**
     * Заголовок письма
     */
    title: string;
    /**
     * Сопроводительное письмо
     */
    coverLetter: string;
    /**
     * Цена
     */
    amount: number;
};

export type InvitationPaginatedResponse = {
    data: Array<InvitationResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateChatDto = {
    /**
     * Текст сообщения
     */
    title: string;
    /**
     * Тип чата
     */
    type: string;
    /**
     * Контекст чата. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    context?: string;
    /**
     * Уникальный идентификатор контекстной сущности, например отклика. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    contextId?: string;
    /**
     * Id участников чата
     */
    membersIds: Array<string>;
};

export type ChatResponseDto = {
    /**
     * Уникальный идентификатор чата
     */
    id: string;
    /**
     * Название чата
     */
    title: string;
    /**
     * Тип чата
     */
    type: string;
    /**
     * Контекст чата. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    context?: {
        [key: string]: unknown;
    };
    /**
     * Уникальный идентификатор контекстной сущности, например отклика. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    contextId?: {
        [key: string]: unknown;
    };
    /**
     * Участники чата
     */
    members: Array<string>;
    /**
     * Если заблокирован чат
     */
    block: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type UpdateChatDto = {
    /**
     * Текст сообщения
     */
    title?: string;
    /**
     * Тип чата
     */
    type?: string;
    /**
     * Контекст чата. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    context?: string;
    /**
     * Уникальный идентификатор контекстной сущности, например отклика. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    contextId?: string;
    /**
     * Id участников чата
     */
    membersIds: Array<string>;
};

export type ChatPaginatedResponse = {
    data: Array<ChatResponseDto>;
    meta: PaginationMetaDto;
};

export type FindMyChatsResponseDto = {
    /**
     * Уникальный идентификатор чата
     */
    id: string;
    /**
     * Название чата
     */
    title: string;
    /**
     * Тип чата
     */
    type: string;
    /**
     * Контекст чата. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    context?: {
        [key: string]: unknown;
    };
    /**
     * Уникальный идентификатор контекстной сущности, например отклика. В случае если тип чата 'DIRECT' принимает значение 'null'
     */
    contextId?: {
        [key: string]: unknown;
    };
    /**
     * Участники чата
     */
    participants: Array<string>;
    /**
     * Последнее сообщение
     */
    lastMessage?: {
        [key: string]: unknown;
    };
    /**
     * Если заблокирован чат
     */
    block: {
        [key: string]: unknown;
    };
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type MyChatPaginatedResponse = {
    data: Array<FindMyChatsResponseDto>;
    meta: PaginationMetaDto;
};

export type CreateMessageDto = {
    /**
     * Уникальный идентификатор чата
     */
    chatId: string;
    /**
     * Текст сообщения
     */
    text: string;
};

export type MessageResponseDto = {
    /**
     * Уникальный идентификатор сообщения
     */
    id: string;
    /**
     * Уникальный идентификатор отправителя
     */
    senderId: string;
    /**
     * Текст сообщения
     */
    text?: {
        [key: string]: unknown;
    };
    /**
     * Url файлов сообщения
     */
    files?: Array<string>;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата последнего обновления
     */
    updatedAt: string;
};

export type BeneficiaryDocumentDto = {
    /**
     * Тип документа
     */
    type: 'PASSPORT' | 'FOREIGN_PASSPORT' | 'CONTRACT_GPD';
    /**
     * Серия документа (для паспорта РФ – 4 цифры)
     */
    serial?: string;
    /**
     * Номер документа
     */
    number: string;
    /**
     * Дата выдачи в формате YYYY-MM-DD
     */
    date: string;
    /**
     * Кем выдан (наименование органа)
     */
    organization?: string;
    /**
     * Код подразделения
     */
    division?: string;
    /**
     * Дата окончания срока действия (если есть)
     */
    expireDate?: string;
};

export type BeneficiaryAddressDto = {
    /**
     * Тип адреса
     */
    type: 'REGISTRATION_ADDRESS' | 'RESIDENCE_ADDRESS' | 'POSTAL_ADDRESS';
    /**
     * Полный почтовый адрес
     */
    address: string;
};

export type BeneficiaryDetailsDto = {
    firstName: string;
    middleName?: string;
    lastName: string;
    isSelfEmployed: boolean;
    birthDate: string;
    birthPlace: string;
    citizenship: string;
    /**
     * Номер телефона в формате E.164 (например, +79161234567)
     */
    phoneNumber: string;
    email: string;
    documents: Array<BeneficiaryDocumentDto>;
    addresses: Array<BeneficiaryAddressDto>;
    inn?: string;
    /**
     * СНИЛС (11 цифр без разделителей)
     */
    snils: string;
};

export type CreateBeneficiaryDto = {
    type: 'FL_RESIDENT' | 'FL_NONRESIDENT' | 'UL_RESIDENT' | 'UL_NONRESIDENT' | 'IP_RESIDENT' | 'IP_NONRESIDENT' | 'LITE_CONTACT';
    details: BeneficiaryDetailsDto;
};

export type BeneficiaryResponseDto = {
    id: string;
    accountId: string;
    type: 'FL_RESIDENT' | 'FL_NONRESIDENT' | 'UL_RESIDENT' | 'UL_NONRESIDENT' | 'IP_RESIDENT' | 'IP_NONRESIDENT' | 'LITE_CONTACT';
    externalId: {
        [key: string]: unknown;
    } | null;
    details: BeneficiaryDetailsDto;
    createdAt: string;
    updatedAt: string;
};

export type UpdateBeneficiaryDetailsDto = {
    firstName?: string;
    middleName?: string;
    lastName?: string;
    isSelfEmployed?: boolean;
    birthDate?: string;
    birthPlace?: string;
    citizenship?: string;
    /**
     * Номер телефона в формате E.164 (например, +79161234567)
     */
    phoneNumber?: string;
    email?: string;
    documents?: Array<BeneficiaryDocumentDto>;
    addresses?: Array<BeneficiaryAddressDto>;
    inn?: string;
    /**
     * СНИЛС (11 цифр без разделителей)
     */
    snils?: string;
};

export type UpdateBeneficiaryDto = {
    type?: 'FL_RESIDENT' | 'FL_NONRESIDENT' | 'UL_RESIDENT' | 'UL_NONRESIDENT' | 'IP_RESIDENT' | 'IP_NONRESIDENT' | 'LITE_CONTACT';
    /**
     * При обновлении полей документов и адресов необходимо передавать изменяемый объект полностью. Конкретный документ или адрес будет перезаписан целиком. Если поле не передано – остаётся без изменений.
     */
    details?: UpdateBeneficiaryDetailsDto;
};

export type BeneficiaryPaginatedResponse = {
    data: Array<BeneficiaryResponseDto>;
    meta: PaginationMetaDto;
};

export type CardDetailsDto = {
    /**
     * Номер карты (16 цифр)
     */
    pan: string;
    /**
     * Срок действия карты в формате MMYY
     */
    expiryDate: string;
    /**
     * Имя держателя карты (как на карте)
     */
    cardHolder?: string;
    /**
     * CVV/CVC код (3 или 4 цифры)
     */
    cvv?: string;
};

export type SbpDetailsDto = {
    /**
     * Номер телефона в формате +7XXXXXXXXXX
     */
    phoneNumber: string;
    /**
     * Идентификатор банка в СБП (12 цифр)
     */
    bankId: string;
};

export type PaymentDetailsDto = {
    /**
     * БИК банка получателя (9 цифр)
     */
    bik: string;
    /**
     * Наименование банка получателя
     */
    bankName: string;
    /**
     * Номер расчетного счета получателя (20 или 22 цифры)
     */
    accountNumber: string;
    /**
     * Корреспондентский счет банка получателя (20 цифр)
     */
    corrAccountNumber: string;
    /**
     * ИНН получателя (10 или 12 цифр)
     */
    inn?: string;
    /**
     * КПП получателя (9 цифр)
     */
    kpp?: string;
    /**
     * Наименование получателя (для юрлиц или ИП)
     */
    name?: string;
};

export type CreateBankDetailsDto = {
    /**
     * UUID бенефициара, к которому добавляются реквизиты
     */
    beneficiaryId: string;
    /**
     * Тип банковских реквизитов
     */
    type: 'CARD' | 'SBP' | 'PAYMENT_DETAILS';
    /**
     * Флаг – являются ли реквизиты основными для бенефициара
     */
    isDefault: boolean;
    /**
     * Данные банковской карты (обязателен при type = CARD)
     */
    card?: CardDetailsDto;
    /**
     * Данные для оплаты через СБП (обязателен при type = SBP)
     */
    sbp?: SbpDetailsDto;
    /**
     * Данные банковского счета (обязателен при type = PAYMENT_DETAILS)
     */
    payment?: PaymentDetailsDto;
};

export type CardDetailsResponseDto = {
    /**
     * Идентификатор карты в банке
     */
    cardId?: string;
    /**
     * Маскированный номер карты (для отображения)
     */
    maskedPan: string;
    /**
     * Месяц окончания срока действия (1-12)
     */
    expiryMonth?: number;
    /**
     * Год окончания срока действия (например, 2028)
     */
    expiryYear?: number;
    /**
     * Имя держателя карты
     */
    cardHolder?: string;
};

export type SbpDetailsResponseDto = {
    /**
     * Маскированный номер телефона (для отображения)
     */
    maskedPhone: string;
    /**
     * Идентификатор банка в СБП
     */
    bankId?: string;
};

export type PaymentDetailsResponseDto = {
    /**
     * Маскированный номер счета (последние 4 цифры)
     */
    maskedAccount: string;
    /**
     * Наименование банка получателя
     */
    bankName: string;
    /**
     * БИК банка получателя
     */
    bik?: string;
};

export type BankDetailsResponseDto = {
    /**
     * Уникальный идентификатор
     */
    id: string;
    /**
     * UUID бенефициара
     */
    beneficiaryId: string;
    /**
     * Тип реквизитов
     */
    type: 'CARD' | 'SBP' | 'PAYMENT_DETAILS';
    /**
     * Детали реквизитов (зависят от типа)
     */
    details: ({
        type: 'CARD';
    } & CardDetailsResponseDto) | ({
        type: 'SBP';
    } & SbpDetailsResponseDto) | ({
        type: 'PAYMENT_DETAILS';
    } & PaymentDetailsResponseDto);
    /**
     * Основные реквизиты
     */
    isDefault: boolean;
    /**
     * Дата создания
     */
    createdAt: string;
    /**
     * Дата обновления
     */
    updatedAt: string;
};

export type BankDetailsPaginatedResponse = {
    data: Array<BankDetailsResponseDto>;
    meta: PaginationMetaDto;
};

export type UpdateBankDetailsDto = {
    /**
     * Флаг – сделать реквизиты основными для бенефициара
     */
    isDefault: boolean;
};

export type ProfilesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор пользователя
         */
        userId?: string;
    };
    url: '/api/profiles';
};

export type ProfilesControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ProfilesControllerFindAllResponses = {
    /**
     * Профили успешно получены
     */
    200: ProfilePaginatedResponse;
};

export type ProfilesControllerFindAllResponse = ProfilesControllerFindAllResponses[keyof ProfilesControllerFindAllResponses];

export type ProfilesControllerCreateData = {
    body: CreateProfileDto;
    path?: never;
    query?: never;
    url: '/api/profiles';
};

export type ProfilesControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type ProfilesControllerCreateResponses = {
    /**
     * Профиль успешно создан
     */
    200: ProfileResponseDto;
};

export type ProfilesControllerCreateResponse = ProfilesControllerCreateResponses[keyof ProfilesControllerCreateResponses];

export type ProfilesControllerUpdateData = {
    body: UpdateProfileDto;
    path: {
        profileId: string;
    };
    query?: never;
    url: '/api/profiles/{profileId}';
};

export type ProfilesControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Профиль не найден
     */
    404: unknown;
};

export type ProfilesControllerUpdateResponses = {
    /**
     * Профиль успешно обновлен
     */
    200: ProfileResponseDto;
};

export type ProfilesControllerUpdateResponse = ProfilesControllerUpdateResponses[keyof ProfilesControllerUpdateResponses];

export type ProfilesControllerFindMyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/my';
};

export type ProfilesControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Профиль не найден
     */
    404: unknown;
};

export type ProfilesControllerFindMyResponses = {
    /**
     * Профиль успешно получен
     */
    200: ProfilePaginatedResponse;
};

export type ProfilesControllerFindMyResponse = ProfilesControllerFindMyResponses[keyof ProfilesControllerFindMyResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Пользователь уже существует
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * Пользователь успешно зарегистрирован
     */
    200: UserResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Сессия создана
     */
    200: boolean;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * Пользователь не авторизован
     */
    401: unknown;
};

export type AuthControllerLogoutResponses = {
    /**
     * Сессия удалена
     */
    200: boolean;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type UsersControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Пользователь уже существует
     */
    409: unknown;
};

export type UsersControllerCreateResponses = {
    /**
     * Пользователь успешно создан
     */
    200: UserResponseDto;
};

export type UsersControllerCreateResponse = UsersControllerCreateResponses[keyof UsersControllerCreateResponses];

export type UsersControllerFindMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UsersControllerFindMeErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type UsersControllerFindMeResponses = {
    /**
     * Пользователь получен
     */
    200: FindMeResponseDto;
};

export type UsersControllerFindMeResponse = UsersControllerFindMeResponses[keyof UsersControllerFindMeResponses];

export type WorkspacesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Название рабочего пространства
         */
        name?: string;
        /**
         * Уникальный идентификатор пользователя
         */
        userId?: string;
    };
    url: '/api/workspaces';
};

export type WorkspacesControllerFindAllErrors = {
    /**
     * Пользователь не авторизован
     */
    401: unknown;
    /**
     * Недостаточно прав
     */
    403: unknown;
    /**
     * Неверные параметры запроса
     */
    404: unknown;
};

export type WorkspacesControllerFindAllResponses = {
    /**
     * Рабочие пространства получены
     */
    200: WorkspacePaginatedResponseDto;
};

export type WorkspacesControllerFindAllResponse = WorkspacesControllerFindAllResponses[keyof WorkspacesControllerFindAllResponses];

export type WorkspacesControllerCreateData = {
    body: CreateWorkspaceDto;
    path?: never;
    query?: never;
    url: '/api/workspaces';
};

export type WorkspacesControllerCreateErrors = {
    /**
     * Пользователь не авторизован
     */
    401: unknown;
    /**
     * Неверные параметры запроса
     */
    404: unknown;
};

export type WorkspacesControllerCreateResponses = {
    /**
     * Рабочее пространство успешно создан
     */
    200: WorkspaceResponseDto;
};

export type WorkspacesControllerCreateResponse = WorkspacesControllerCreateResponses[keyof WorkspacesControllerCreateResponses];

export type WorkspacesControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
    };
    url: '/api/workspaces/my';
};

export type WorkspacesControllerFindMyErrors = {
    /**
     * Пользователь не авторизован
     */
    401: unknown;
    /**
     * Недостаточно прав
     */
    403: unknown;
    /**
     * Неверные параметры запроса
     */
    404: unknown;
};

export type WorkspacesControllerFindMyResponses = {
    /**
     * Рабочие пространства получены
     */
    200: WorkspacePaginatedResponseDto;
};

export type WorkspacesControllerFindMyResponse = WorkspacesControllerFindMyResponses[keyof WorkspacesControllerFindMyResponses];

export type AccountsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор пользователя
         */
        userId?: string;
    };
    url: '/api/accounts';
};

export type AccountsControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type AccountsControllerFindAllResponses = {
    /**
     * Аккаунты успешно получены
     */
    200: AccountPaginatedResponse;
};

export type AccountsControllerFindAllResponse = AccountsControllerFindAllResponses[keyof AccountsControllerFindAllResponses];

export type AccountsControllerCreateData = {
    body: CreateAccountDto;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type AccountsControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type AccountsControllerCreateResponses = {
    /**
     * Аккаунт успешно создан
     */
    200: AccountResponseDto;
};

export type AccountsControllerCreateResponse = AccountsControllerCreateResponses[keyof AccountsControllerCreateResponses];

export type AccountsControllerUpdateData = {
    body: UpdateAccountDto;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type AccountsControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Аккаунт не найден
     */
    404: unknown;
};

export type AccountsControllerUpdateResponses = {
    /**
     * Аккаунт успешно обновлён
     */
    200: AccountResponseDto;
};

export type AccountsControllerUpdateResponse = AccountsControllerUpdateResponses[keyof AccountsControllerUpdateResponses];

export type AccountsControllerFindMyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/my';
};

export type AccountsControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Аккаунт не найден
     */
    404: unknown;
};

export type AccountsControllerFindMyResponses = {
    /**
     * Аккаунт успешно получен
     */
    200: AccountPaginatedResponse;
};

export type AccountsControllerFindMyResponse = AccountsControllerFindMyResponses[keyof AccountsControllerFindMyResponses];

export type ProjectsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор владельца проекта
         */
        userId?: string;
    };
    url: '/api/projects';
};

export type ProjectsControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ProjectsControllerFindAllResponses = {
    /**
     * Проекты успешно получены
     */
    200: ProjectPaginatedResponse;
};

export type ProjectsControllerFindAllResponse = ProjectsControllerFindAllResponses[keyof ProjectsControllerFindAllResponses];

export type ProjectsControllerCreateData = {
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ProjectsControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ProjectsControllerCreateResponses = {
    /**
     * Проект успешно создан
     */
    200: ProjectResponseDto;
};

export type ProjectsControllerCreateResponse = ProjectsControllerCreateResponses[keyof ProjectsControllerCreateResponses];

export type ProjectsControllerFindByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{id}';
};

export type ProjectsControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ProjectsControllerFindByIdResponses = {
    /**
     * Проект успешно обновлен
     */
    200: ProjectResponseDto;
};

export type ProjectsControllerFindByIdResponse = ProjectsControllerFindByIdResponses[keyof ProjectsControllerFindByIdResponses];

export type ProjectsControllerUpdateData = {
    body: UpdateProjectDto;
    path?: never;
    query?: never;
    url: '/api/projects/{id}';
};

export type ProjectsControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ProjectsControllerUpdateResponses = {
    /**
     * Проект успешно обновлен
     */
    200: ProjectResponseDto;
};

export type ProjectsControllerUpdateResponse = ProjectsControllerUpdateResponses[keyof ProjectsControllerUpdateResponses];

export type ProjectsControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
    };
    url: '/api/projects/my';
};

export type ProjectsControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ProjectsControllerFindMyResponses = {
    /**
     * Проект успешно обновлен
     */
    200: ProjectPaginatedResponse;
};

export type ProjectsControllerFindMyResponse = ProjectsControllerFindMyResponses[keyof ProjectsControllerFindMyResponses];

export type TasksControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор пользователя
         */
        userId?: string;
        /**
         * Заголовок задачи. Поиск по совпадению
         */
        title?: string;
        /**
         * Описание задачи. Поиск по совпадению
         */
        description?: string;
        /**
         * Только (не)опубликованные задачи
         */
        isPublished?: boolean;
        /**
         * Минимальная цена. Поиск больше или равно указанного значения
         */
        minPrice?: number;
        /**
         * Максимальная цена. Поиск меньше или равно указанного значения
         */
        maxPrice?: number;
        /**
         * Искать задачи только без откликов
         */
        notBids?: boolean;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Статус задачи
         */
        status?: string;
        /**
         * Массив идентификаторов категорий
         */
        categoryIds?: Array<string>;
    };
    url: '/api/tasks';
};

export type TasksControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type TasksControllerFindAllResponses = {
    /**
     * Задачи успешно получены
     */
    200: TaskForDetailsPaginatedResponse;
};

export type TasksControllerFindAllResponse = TasksControllerFindAllResponses[keyof TasksControllerFindAllResponses];

export type TasksControllerCreateData = {
    body: CreateTaskDto;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type TasksControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Неверные параметры запрос
     */
    404: unknown;
};

export type TasksControllerCreateResponses = {
    /**
     * Задача успешно создана
     */
    200: TaskResponseDto;
};

export type TasksControllerCreateResponse = TasksControllerCreateResponses[keyof TasksControllerCreateResponses];

export type TasksControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type TasksControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Задача не найдена
     */
    404: unknown;
};

export type TasksControllerFindByIdResponses = {
    /**
     * Задача успешно получена
     */
    200: TaskResponseForDetailsDto;
};

export type TasksControllerFindByIdResponse = TasksControllerFindByIdResponses[keyof TasksControllerFindByIdResponses];

export type TasksControllerUpdateData = {
    body: UpdateTaskDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type TasksControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Задача не найдена
     */
    404: unknown;
};

export type TasksControllerUpdateResponses = {
    /**
     * Задача успешно обновлена
     */
    200: TaskResponseDto;
};

export type TasksControllerUpdateResponse = TasksControllerUpdateResponses[keyof TasksControllerUpdateResponses];

export type ServiceControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор пользователя
         */
        userId?: string;
        /**
         * Название услуги. Поиск по совпадению
         */
        title?: string;
        /**
         * Описание услуги. Поиск по совпадению
         */
        description?: string;
        /**
         * Только (не)опубликованные услуги
         */
        isPublished?: boolean;
        /**
         * Минимальная цена. Поиск больше или равно указанного значения
         */
        minPrice?: number;
        /**
         * Максимальная цена. Поиск меньше или равно указанного значения
         */
        maxPrice?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Массив идентификаторов категорий
         */
        categoryIds?: Array<string>;
    };
    url: '/api/services';
};

export type ServiceControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ServiceControllerFindAllResponses = {
    /**
     * Услуги успешно получены
     */
    200: ServiceForDetailsPaginatedResponse;
};

export type ServiceControllerFindAllResponse = ServiceControllerFindAllResponses[keyof ServiceControllerFindAllResponses];

export type ServiceControllerCreateData = {
    body: CreateServiceDto;
    path?: never;
    query?: never;
    url: '/api/services';
};

export type ServiceControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ServiceControllerCreateResponses = {
    /**
     * Услуга успешно создана
     */
    200: ServiceResponseDto;
};

export type ServiceControllerCreateResponse = ServiceControllerCreateResponses[keyof ServiceControllerCreateResponses];

export type ServiceControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/services/{id}';
};

export type ServiceControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ServiceControllerFindByIdResponses = {
    /**
     * Услуга успешно получена
     */
    200: ServiceResponseForDetailsDto;
};

export type ServiceControllerFindByIdResponse = ServiceControllerFindByIdResponses[keyof ServiceControllerFindByIdResponses];

export type ServiceControllerUpdateData = {
    body: UpdateServiceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/services/{id}';
};

export type ServiceControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ServiceControllerUpdateResponses = {
    /**
     * Услуга успешно обновлена
     */
    200: ServiceResponseDto;
};

export type ServiceControllerUpdateResponse = ServiceControllerUpdateResponses[keyof ServiceControllerUpdateResponses];

export type ServiceControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Название услуги. Поиск по совпадению
         */
        title?: string;
        /**
         * Описание услуги. Поиск по совпадению
         */
        description?: string;
        /**
         * Только (не)опубликованные услуги
         */
        isPublished?: boolean;
        /**
         * Минимальная цена. Поиск больше или равно указанного значения
         */
        minPrice?: number;
        /**
         * Максимальная цена. Поиск меньше или равно указанного значения
         */
        maxPrice?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Массив идентификаторов категорий
         */
        categoryIds?: Array<string>;
    };
    url: '/api/services/my';
};

export type ServiceControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ServiceControllerFindMyResponses = {
    /**
     * Услуги успешно получены
     */
    200: ServiceForDetailsPaginatedResponse;
};

export type ServiceControllerFindMyResponse = ServiceControllerFindMyResponses[keyof ServiceControllerFindMyResponses];

export type ContractControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор пользователя (возвращает контракты, где пользователь является либо заказчиком, либо исполнителем)
         */
        userId?: string;
        /**
         * Уникальный идентификатор заказчика
         */
        clientId?: string;
        /**
         * Уникальный идентификатор исполнителя
         */
        contractorId?: string;
        /**
         * Минимальная сумма контракта. Поиск больше или равно указанного значения
         */
        amountMin?: number;
        /**
         * Максимальная сумма контракта. Поиск меньше или равно указанного значения
         */
        amountMax?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор задачи
         */
        taskId?: string;
        /**
         * Уникальный идентификатор услуги
         */
        serviceId?: string;
    };
    url: '/api/contracts';
};

export type ContractControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ContractControllerFindAllResponses = {
    /**
     * Контракты успешно получены
     */
    200: ContractPaginatedResponse;
};

export type ContractControllerFindAllResponse = ContractControllerFindAllResponses[keyof ContractControllerFindAllResponses];

export type ContractControllerCreateData = {
    body: CreateContractDto;
    path?: never;
    query?: never;
    url: '/api/contracts';
};

export type ContractControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ContractControllerCreateResponses = {
    /**
     * Контракт успешно создан
     */
    200: ContractResponseDto;
};

export type ContractControllerCreateResponse = ContractControllerCreateResponses[keyof ContractControllerCreateResponses];

export type ContractControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/contracts/{id}';
};

export type ContractControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ContractControllerFindByIdResponses = {
    /**
     * Контракт успешно получен
     */
    200: ContractResponseDto;
};

export type ContractControllerFindByIdResponse = ContractControllerFindByIdResponses[keyof ContractControllerFindByIdResponses];

export type ContractControllerUpdateData = {
    body: UpdateContractDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/contracts/{id}';
};

export type ContractControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ContractControllerUpdateResponses = {
    /**
     * Контракт успешно обновлён
     */
    200: ContractResponseDto;
};

export type ContractControllerUpdateResponse = ContractControllerUpdateResponses[keyof ContractControllerUpdateResponses];

export type ContractControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Минимальная сумма контракта. Поиск больше или равно указанного значения
         */
        amountMin?: number;
        /**
         * Максимальная сумма контракта. Поиск меньше или равно указанного значения
         */
        amountMax?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор задачи
         */
        taskId?: string;
        /**
         * Уникальный идентификатор услуги
         */
        serviceId?: string;
    };
    url: '/api/contracts/my';
};

export type ContractControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ContractControllerFindMyResponses = {
    /**
     * Контракты успешно получены
     */
    200: ContractPaginatedResponse;
};

export type ContractControllerFindMyResponse = ContractControllerFindMyResponses[keyof ContractControllerFindMyResponses];

export type BidsControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Цена отклика. Поиск больше или равно указанного значения
         */
        amountStart?: number;
        /**
         * Цена отклика. Поиск меньше или равно указанного значения
         */
        amountEnd?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
    };
    url: '/api/bids';
};

export type BidsControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type BidsControllerFindMyResponses = {
    /**
     * Отклики успешно получены
     */
    200: BidPaginatedResponse;
};

export type BidsControllerFindMyResponse = BidsControllerFindMyResponses[keyof BidsControllerFindMyResponses];

export type BidsControllerCreateData = {
    body: CreateBidDto;
    path?: never;
    query?: never;
    url: '/api/bids';
};

export type BidsControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type BidsControllerCreateResponses = {
    /**
     * Отклик успешно создан
     */
    200: BidResponseDto;
};

export type BidsControllerCreateResponse = BidsControllerCreateResponses[keyof BidsControllerCreateResponses];

export type BidsControllerFindByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bids/{id}';
};

export type BidsControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type BidsControllerFindByIdResponses = {
    /**
     * Проект успешно получен
     */
    200: BidResponseDto;
};

export type BidsControllerFindByIdResponse = BidsControllerFindByIdResponses[keyof BidsControllerFindByIdResponses];

export type BidsControllerUpdateData = {
    body: UpdateBidDto;
    path?: never;
    query?: never;
    url: '/api/bids/{id}';
};

export type BidsControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type BidsControllerUpdateResponses = {
    /**
     * Отклик успешно обновлен
     */
    200: BidResponseDto;
};

export type BidsControllerUpdateResponse = BidsControllerUpdateResponses[keyof BidsControllerUpdateResponses];

export type InvitationsControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор проекта
         */
        projectId?: string;
        /**
         * Уникальный идентификатор рабочего пространства
         */
        workspaceId?: string;
        /**
         * Уникальный идентификатор владельца приглашения
         */
        senderId?: string;
        /**
         * Уникальный идентификатор получателя приглашения
         */
        recipientId?: string;
    };
    url: '/api/invitations';
};

export type InvitationsControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type InvitationsControllerFindMyResponses = {
    /**
     * Приглашения успешно получены
     */
    200: InvitationPaginatedResponse;
};

export type InvitationsControllerFindMyResponse = InvitationsControllerFindMyResponses[keyof InvitationsControllerFindMyResponses];

export type InvitationsControllerCreateData = {
    body: CreateInvitationDto;
    path?: never;
    query?: never;
    url: '/api/invitations';
};

export type InvitationsControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type InvitationsControllerCreateResponses = {
    /**
     * Приглашение успешно создано
     */
    200: InvitationResponseDto;
};

export type InvitationsControllerCreateResponse = InvitationsControllerCreateResponses[keyof InvitationsControllerCreateResponses];

export type InvitationsControllerFindByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/invitations/{id}';
};

export type InvitationsControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type InvitationsControllerFindByIdResponses = {
    /**
     * Приглашение успешно обновлен
     */
    200: InvitationResponseDto;
};

export type InvitationsControllerFindByIdResponse = InvitationsControllerFindByIdResponses[keyof InvitationsControllerFindByIdResponses];

export type InvitationsControllerUpdateData = {
    body: UpdateInvitationDto;
    path?: never;
    query?: never;
    url: '/api/invitations/{id}';
};

export type InvitationsControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type InvitationsControllerUpdateResponses = {
    /**
     * Приглашение успешно обновлен
     */
    200: InvitationResponseDto;
};

export type InvitationsControllerUpdateResponse = InvitationsControllerUpdateResponses[keyof InvitationsControllerUpdateResponses];

export type ChatControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Текст сообщения
         */
        title?: string;
        /**
         * Тип чата
         */
        type?: string;
        /**
         * Контекст чата
         */
        context?: string;
        /**
         * Уникальный идентификатор контекстной сущности, например отклика.
         */
        contextId?: string;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор отправителя сообщения
         */
        senderId?: string;
        /**
         * Уникальный идентификатор задачи
         */
        chatId?: string;
    };
    url: '/api/chats';
};

export type ChatControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type ChatControllerFindAllResponses = {
    /**
     * Чаты успешно получены
     */
    200: ChatPaginatedResponse;
};

export type ChatControllerFindAllResponse = ChatControllerFindAllResponses[keyof ChatControllerFindAllResponses];

export type ChatControllerCreateData = {
    body: CreateChatDto;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type ChatControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ChatControllerCreateResponses = {
    /**
     * Чат успешно создан
     */
    200: ChatResponseDto;
};

export type ChatControllerCreateResponse = ChatControllerCreateResponses[keyof ChatControllerCreateResponses];

export type ChatControllerFindByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats/{id}';
};

export type ChatControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ChatControllerFindByIdResponses = {
    /**
     * Чат успешно получен
     */
    200: ChatResponseDto;
};

export type ChatControllerFindByIdResponse = ChatControllerFindByIdResponses[keyof ChatControllerFindByIdResponses];

export type ChatControllerUpdateData = {
    body: UpdateChatDto;
    path?: never;
    query?: never;
    url: '/api/chats/{id}';
};

export type ChatControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ChatControllerUpdateResponses = {
    /**
     * Чат успешно обновлен
     */
    200: ChatResponseDto;
};

export type ChatControllerUpdateResponse = ChatControllerUpdateResponses[keyof ChatControllerUpdateResponses];

export type ChatControllerFindMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Текст сообщения
         */
        title?: string;
        /**
         * Тип чата
         */
        type?: string;
        /**
         * Контекст чата
         */
        context?: string;
        /**
         * Уникальный идентификатор контекстной сущности, например отклика.
         */
        contextId?: string;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор отправителя сообщения
         */
        senderId?: string;
        /**
         * Уникальный идентификатор задачи
         */
        chatId?: string;
    };
    url: '/api/chats/my';
};

export type ChatControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type ChatControllerFindMyResponses = {
    /**
     * Чаты успешно получены
     */
    200: MyChatPaginatedResponse;
};

export type ChatControllerFindMyResponse = ChatControllerFindMyResponses[keyof ChatControllerFindMyResponses];

export type MessageControllerFindAllData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Текст сообщения. Поиск по совпадению
         */
        text?: string;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
        /**
         * Уникальный идентификатор отправителя сообщения
         */
        senderId?: string;
        /**
         * Уникальный идентификатор задачи
         */
        chatId: string;
    };
    url: '/api/messages';
};

export type MessageControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type MessageControllerFindAllResponses = {
    /**
     * Сообщения успешно получены
     */
    200: MessageResponseDto;
};

export type MessageControllerFindAllResponse = MessageControllerFindAllResponses[keyof MessageControllerFindAllResponses];

export type MessageControllerCreateData = {
    body: CreateMessageDto;
    path?: never;
    query?: never;
    url: '/api/messages';
};

export type MessageControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type MessageControllerCreateResponses = {
    /**
     * Сообщение успешно создано
     */
    200: ChatResponseDto;
};

export type MessageControllerCreateResponse = MessageControllerCreateResponses[keyof MessageControllerCreateResponses];

export type BeneficiaryControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Уникальный идентификатор аккаунта
         */
        accountId?: string;
        /**
         * Тип бенефициара
         */
        type?: string;
        /**
         * Дата создания. Поиск больше или равно указанного значения
         */
        createdAtStart?: string;
        /**
         * Дата создания. Поиск меньше или равно указанного значения
         */
        createdAtEnd?: string;
    };
    url: '/api/beneficiary';
};

export type BeneficiaryControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type BeneficiaryControllerFindAllResponses = {
    /**
     * Список успешно получен
     */
    200: BeneficiaryPaginatedResponse;
};

export type BeneficiaryControllerFindAllResponse = BeneficiaryControllerFindAllResponses[keyof BeneficiaryControllerFindAllResponses];

export type BeneficiaryControllerCreateData = {
    body: CreateBeneficiaryDto;
    path?: never;
    query?: never;
    url: '/api/beneficiary';
};

export type BeneficiaryControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type BeneficiaryControllerCreateResponses = {
    /**
     * Бенефициар успешно создан
     */
    200: BeneficiaryResponseDto;
};

export type BeneficiaryControllerCreateResponse = BeneficiaryControllerCreateResponses[keyof BeneficiaryControllerCreateResponses];

export type BeneficiaryControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/beneficiary/{id}';
};

export type BeneficiaryControllerRemoveErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type BeneficiaryControllerRemoveResponses = {
    /**
     * Бенефициар успешно удален
     */
    200: unknown;
};

export type BeneficiaryControllerUpdateData = {
    body: UpdateBeneficiaryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/beneficiary/{id}';
};

export type BeneficiaryControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
};

export type BeneficiaryControllerUpdateResponses = {
    /**
     * Бенефициар успешно обновлен
     */
    200: BeneficiaryResponseDto;
};

export type BeneficiaryControllerUpdateResponse = BeneficiaryControllerUpdateResponses[keyof BeneficiaryControllerUpdateResponses];

export type BeneficiaryControllerFindMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/beneficiary/me';
};

export type BeneficiaryControllerFindMeErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Бенефициар не найден
     */
    404: unknown;
};

export type BeneficiaryControllerFindMeResponses = {
    /**
     * Бенефициар успешно получен
     */
    200: Array<BeneficiaryResponseDto>;
};

export type BeneficiaryControllerFindMeResponse = BeneficiaryControllerFindMeResponses[keyof BeneficiaryControllerFindMeResponses];

export type BankDetailsControllerFindAllData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Номер страницы
         */
        page?: number;
        /**
         * Количество элементов на странице
         */
        limit?: number;
        /**
         * Фильтр по идентификатору бенефициара
         */
        beneficiaryId?: string;
        /**
         * Тип банковских реквизитов
         */
        type: 'CARD' | 'SBP' | 'PAYMENT_DETAILS';
    };
    url: '/api/bank-details';
};

export type BankDetailsControllerFindAllErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
};

export type BankDetailsControllerFindAllResponses = {
    /**
     * Список успешно получен
     */
    200: BankDetailsPaginatedResponse;
};

export type BankDetailsControllerFindAllResponse = BankDetailsControllerFindAllResponses[keyof BankDetailsControllerFindAllResponses];

export type BankDetailsControllerCreateData = {
    body: CreateBankDetailsDto;
    path?: never;
    query?: never;
    url: '/api/bank-details';
};

export type BankDetailsControllerCreateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Бенефициар не найден
     */
    404: unknown;
};

export type BankDetailsControllerCreateResponses = {
    /**
     * Реквизиты успешно добавлены
     */
    200: BankDetailsResponseDto;
};

export type BankDetailsControllerCreateResponse = BankDetailsControllerCreateResponses[keyof BankDetailsControllerCreateResponses];

export type BankDetailsControllerFindMyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bank-details/me';
};

export type BankDetailsControllerFindMyErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Бенефициар не найден
     */
    404: unknown;
};

export type BankDetailsControllerFindMyResponses = {
    /**
     * Список успешно получен
     */
    200: Array<BankDetailsResponseDto>;
};

export type BankDetailsControllerFindMyResponse = BankDetailsControllerFindMyResponses[keyof BankDetailsControllerFindMyResponses];

export type BankDetailsControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bank-details/{id}';
};

export type BankDetailsControllerDeleteErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Реквизиты не найдены
     */
    404: unknown;
};

export type BankDetailsControllerDeleteResponses = {
    /**
     * Реквизиты успешно удалены
     */
    200: unknown;
};

export type BankDetailsControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bank-details/{id}';
};

export type BankDetailsControllerFindByIdErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Реквизиты не найдены
     */
    404: unknown;
};

export type BankDetailsControllerFindByIdResponses = {
    /**
     * Реквизиты успешно получены
     */
    200: BankDetailsResponseDto;
};

export type BankDetailsControllerFindByIdResponse = BankDetailsControllerFindByIdResponses[keyof BankDetailsControllerFindByIdResponses];

export type BankDetailsControllerUpdateData = {
    body: UpdateBankDetailsDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bank-details/{id}';
};

export type BankDetailsControllerUpdateErrors = {
    /**
     * Не авторизован
     */
    401: unknown;
    /**
     * Нет доступа
     */
    403: unknown;
    /**
     * Реквизиты не найдены
     */
    404: unknown;
};

export type BankDetailsControllerUpdateResponses = {
    /**
     * Реквизиты успешно обновлены
     */
    200: BankDetailsResponseDto;
};

export type BankDetailsControllerUpdateResponse = BankDetailsControllerUpdateResponses[keyof BankDetailsControllerUpdateResponses];
